# Generated by Django 4.2 on 2025-02-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
